[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "chmod +x build.sh && ./build.sh"
  publish = "build/web"

[context.deploy-preview]
  command = "chmod +x build.sh && ./build.sh"
  publish = "build/web"
